# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
min_fastlane_version("2.73.0")

default_platform(:ios)

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    # cocoapods
    # cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    run_tests
  end

  lane :screenshot do

   # capture_screenshots
   # capture_screenshots(number_of_retries: 3)

    #frame_screenshots(white: true)
    build_app(scheme: "TodayDo")
    #upload_to_app_store                  # upload your app to iTunes Connect

  end

  lane :update do 
    sync_code_signing(type: "appstore")

    gym(scheme: "TodayDo", 
	 export_method: "app-store")

    upload_to_app_store

    deliver(
  	submit_for_review: true,
  	force: true,
    skip_binary_upload: true,
  	metadata_path: "./metadata",
    submission_information: {
      add_id_info_limits_tracking: true,
      add_id_info_serves_ads: true,
      add_id_info_tracks_action: true,
      add_id_info_tracks_install: true,
      add_id_info_uses_idfa: true,
      content_rights_has_rights: true,
      content_rights_contains_third_party_content: true,
      export_compliance_platform: 'ios',
      export_compliance_compliance_required: false,
      export_compliance_encryption_updated: false,
      export_compliance_app_type: nil,
      export_compliance_uses_encryption: false,
      export_compliance_is_exempt: false,
      export_compliance_contains_third_party_cryptography: false,
      export_compliance_contains_proprietary_cryptography: false,
      export_compliance_available_on_french_store: false
    }
    )
   end




  lane :release do
# capture_screenshots(number_of_retries: 3)

   #upload_to_app_store

#   produce(
#    username: 'mrblue.dev@gmail.com',
#    app_identifier: 'com.mrbluetest.todaydo.ios',
#    app_name: 'TodayDo',
#    language: 'Korean',
#    app_version: '1.0')
  
  # build_app(scheme: "TodayDo")

  deliver(
  	submit_for_review: true,
  	force: true,
    skip_binary_upload: true,
  	metadata_path: "./metadata",
	ipa: ".",
    submission_information: {
      add_id_info_limits_tracking: true,
      add_id_info_serves_ads: true,
      add_id_info_tracks_action: true,
      add_id_info_tracks_install: true,
      add_id_info_uses_idfa: true,
      content_rights_has_rights: true,
      content_rights_contains_third_party_content: true,
      export_compliance_platform: 'ios',
      export_compliance_compliance_required: false,
      export_compliance_encryption_updated: false,
      export_compliance_app_type: nil,
      export_compliance_uses_encryption: false,
      export_compliance_is_exempt: false,
      export_compliance_contains_third_party_cryptography: false,
      export_compliance_contains_proprietary_cryptography: false,
      export_compliance_available_on_french_store: false
    }
    )


#    sync_code_signing(type: "appstore")

#    build_app(scheme: "TodayDo")

    deliver(
  	submit_for_review: true,
  	force: true,
       skip_binary_upload: true,
  	metadata_path: "./fastlane/metadata",
#       app_version: "1.0.2",
       automatic_release: true,
    submission_information: {
      add_id_info_limits_tracking: true,
      add_id_info_serves_ads: true,
      add_id_info_tracks_action: true,
      add_id_info_tracks_install: true,
      add_id_info_uses_idfa: true,
      content_rights_has_rights: true,
      content_rights_contains_third_party_content: true,
      export_compliance_platform: 'ios',
      export_compliance_compliance_required: false,
      export_compliance_encryption_updated: false,
      export_compliance_app_type: nil,
      export_compliance_uses_encryption: false,
      export_compliance_is_exempt: false,
      export_compliance_contains_third_party_cryptography: false,
      export_compliance_contains_proprietary_cryptography: false,
      export_compliance_available_on_french_store: false
    }
    )




  end


  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # sync_code_signing(type: "appstore") # more information: https://codesigning.guide
    build_app # more options available
    upload_to_testflight

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
#  lane :release do
#    # sync_code_signing(type: "appstore")
#    capture_screenshots
#    build_app # more options available
#    upload_to_app_store(force: true)
#    # frame_screenshots
#  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://docs.fastlane.tools/advanced/#control-configuration-by-lane-and-by-platform
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics
